build:
  maxIssues: 1
  weights:
     complexity: 1
     LongParameterList: 1
     style: 1
     comments: 0
     empty-blocks: 1
     exceptions: 0
     naming: 1
     performance: 1
     potential-bugs: 1

output-reports:
  active: true
  exclude:
    - 'PlainOutputReport'
    - 'XmlOutputReport'

comments:
  active: false

complexity:
  active: true
  ComplexCondition:
    active: true
    thresh